### ISSUE TITLE
Mapa Mental

### ISSUE THREAD

**Issue by ArturoAngonJose** [SistemasTecTlaxiaco/mapa-mental-web-3-ArturoAngonJose#1]
[Mapa Mental.pdf](https://github.com/SistemasTecTlaxiaco/mapa-mental-web-3-ArturoAngonJose/files/8395008/Mapa.Mental.pdf)

**Comment by javiern-778** [comment]
calificaion 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
